# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions. The text below code cell is the expected output.

You are all required to upload this file on github before 23:59 on 19/05/2023.

#### Import NumPy as np

In [6]:
import numpy as np

#### Create an array of 10 zeros 

In [11]:
array1=np.zeros(10)
array1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [12]:
array2=np.ones(10)
array2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [13]:
array3=np.linspace(5,5,num=10)
array3

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [14]:
array4=np.arange(10,51)
array4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [ ]:
array5=np.arange(10,51,2)
array5

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
array6=np.arange(0,9).reshape((3,3))
array6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [ ]:
array7=np.identity(3)
array7

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [15]:
import random
num1=random.random()
array8=np.array(num1).reshape(1)
array8

array([0.91826925])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
array9=np.random.randn(25)
array9

array([-0.30994543, -1.71346602,  0.79686039, -0.22295901,  0.00804577,
        0.65976282, -1.65218728, -1.10795795,  0.24541563, -0.16046883,
        0.48729229,  0.64571041, -1.15406944, -0.44500943, -1.06500559,
        1.07255411, -0.77972039, -0.75829935,  0.97133043, -0.65665892,
        2.24515872, -1.53367049,  0.9911956 , -1.39714945, -1.05173999])

#### Create the following matrix:

In [ ]:
array10=np.linspace(0.01,1,num=100).reshape(10,10)
array10

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
array11=np.linspace(0,1,num=20).reshape(1,20)
array11

array([[0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
        0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
        0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
        0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ]])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [7]:
array12=np.arange(1,26,dtype=np.int64).reshape(5,5)
array12

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
array13=np.concatenate((np.arange(12,16),np.arange(17,21),np.arange(22,26))).reshape(3,4)
array13

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
array14=np.array(20)
print(array14)

20


In [ ]:
array15=np.arange(2,13,step=5).reshape(3,1)
array15

array([[ 2],
       [ 7],
       [12]])

In [ ]:
array16=np.arange(21,26)
array16

array([21, 22, 23, 24, 25])

In [ ]:
array17=np.arange(16,26).reshape(2,5)
array17

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [8]:
array12.sum()

325

#### Get the standard deviation of the values in mat

In [9]:
array12.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [10]:
array12.sum(axis=0)

array([55, 60, 65, 70, 75])

# Great Job!