# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions. The text below code cell is the expected output.

You are all required to upload this file on github before 23:59 on 19/05/2023.

#### Import NumPy as np

In [1]:
import numpy as np


#### Create an array of 10 zeros 

In [27]:
a=[]
k=0.
for x in range (10):
    a.append(k)

print(a)        



[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


#### Create an array of 10 ones

In [26]:
a=[]
k=1.
for x in range (10):
    a.append(k)
print(a) 

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


#### Create an array of 10 fives

In [23]:
a=[]
k=5.
for x in range (10):
    a.append(k)
print(a)

[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]


#### Create an array of the integers from 10 to 50

In [22]:
a=[]
for x in range (10,51):
    k=x
    a.append(k)
print(a)    

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


#### Create an array of all the even integers from 10 to 50

In [21]:
a=[]
for x in range (10,51,2):
    k=x
    a.append(k)
print(a)

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [20]:
a=[[0,1,2],[3,4,5],[6,7,8]]
print(a)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


#### Create a 3x3 identity matrix

In [19]:
import numpy as np
a=np.zeros((3,3))
for x in range (3):
   for y in range (3):
       if x==y:
           a[x][y]=1.
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [17]:
import numpy as np
a=np.random.normal(0,1)
print(a)

0.18956352956052216


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [16]:
import numpy as np
a = np.random.normal(size=25)
print(a)

[ 1.41192157  0.82583533  0.01187869  0.08650341 -1.14390035  2.05643791
 -1.79977329  0.1111543  -0.31386008  0.26885517  0.56663661  0.11908504
  0.6619858   0.16418137 -0.09122671 -1.10883596 -0.68047574  1.36285228
 -0.11524165 -0.17983876 -0.74987297 -0.36194876 -0.96557206  0.17492973
 -1.99924906]


#### Create the following matrix:

In [ ]:
import numpy as np
a=np.zeros((10,10))
k=0.01
for x in range (10):
    for y in range (10):
        a[x][y]=float(k)
        k=k+0.01


: 

#### Create an array of 20 linearly spaced points between 0 and 1:

In [15]:
import numpy as np
a=np.zeros((1,20))
a=np.linspace(0,1,20)
print(a)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [13]:
import numpy as np
a=np.zeros((5,5))
k=1
for x in range(5):
    for y in range (5):
        a[x][y]=k
        k+=1

In [28]:
import numpy as np
a=np.zeros((5,5))
k=1
for x in range(5):
    for y in range (5):
        a[x][y]=k
        k+=1
print(a[0:3])

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]


In [29]:
import numpy as np
a=np.zeros((5,5))
k=1
for x in range(5):
    for y in range (5):
        a[x][y]=k
        k+=1
print(a[3,4])

20.0


In [30]:
import numpy as np
a=np.zeros((5,5))
k=1
for x in range(5):
    for y in range (5):
        a[x][y]=k
        k+=1
print(a[0:3,1])   

[ 2.  7. 12.]


In [31]:
import numpy as np
a=np.zeros((5,5))
k=1
for x in range(5):
    for y in range (5):
        a[x][y]=k
        k+=1
print(a[4])

[21. 22. 23. 24. 25.]


In [33]:
import numpy as np
a=np.zeros((5,5))
k=1
for x in range(5):
    for y in range (5):
        a[x][y]=k
        k+=1
print(a[3:5])

[[16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]


### Now do the following

#### Get the sum of all the values in mat

In [34]:
import numpy as np
a=np.zeros((5,5))
k=1
for x in range(5):
    for y in range (5):
        a[x][y]=k
        k+=1
add=0
for i in range(5):
    for j in range (5):
        add+=a[i][j]
print(add)

325.0


#### Get the standard deviation of the values in mat

In [35]:
import numpy as np
a=np.zeros((5,5))
k=1
for x in range(5):
    for y in range (5):
        a[x][y]=k
        k+=1
add1=0
for i in range(5):
    for j in range (5):
        add1+=a[i][j]
avg=add1/25
add2=0
for i in range(5):
    for j in range (5):
        add2+=(a[i][j]-avg)**2
add2/=25
std=add2**(0.5)
print(std)

7.211102550927978


#### Get the sum of all the columns in mat

In [36]:
import numpy as np
a=np.zeros((5,5))
k=1
for x in range(5):
    for y in range (5):
        a[x][y]=k
        k+=1
p=np.zeros((5))
for i in range (5):
    for j in range (5):
        p[i]+=a[j][i]
print(p)

[55. 60. 65. 70. 75.]


# Great Job!