# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions. The text below code cell is the expected output.

You are all required to upload this file on github before 23:59 on 19/05/2023.

#### Import NumPy as np

In [8]:
!pip install numpy

     |████████████████████████████████| 15.7MB 4.0MB/s eta 0:00:01


In [15]:
!pip list

Package Version
------- -------
numpy   1.21.6 


In [3]:
import numpy as np

create an array of 10 zeros

In [8]:
import numpy as np

zeros_array = np.zeros(10)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [4]:
ones_array = np.ones(10)
print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [28]:
a = [5.,5.,5.,5.,5.,5.,5.,5.,5.,5.]
b = np.array(a)
b

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [22]:
array1 = np.arange(10,51,1)
array1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [25]:
array1 = np.arange(10,51,2)
array1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
matrix1 = [[0, 1, 2],[3, 4, 5],[6, 7, 8]]
array1 = np.array(matrix1)
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [18]:
array1 = np.eye(3)
array1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [26]:
a = np.random.rand(1)
x = np.array(a)
x

array([0.87862954])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [27]:
np.random.randn(5,5)

array([[ 1.34638509, -0.5515811 ,  0.16563925, -0.06652434,  0.22310794],
       [-0.22194592,  0.51590096,  0.62338588,  0.47062552,  0.87210949],
       [-0.19022343, -0.35530893, -0.54345607, -0.07442205, -0.84546062],
       [-2.69949937, -0.94411146, -0.62525211, -1.27209295, -0.27594484],
       [ 0.11018263,  0.9808683 ,  0.45848523, -0.91707993,  0.63931262]])

#### Create the following matrix:

In [78]:
a = np.arange(0.01,1.01,0.01)
b = np.array(a)
x = b.reshape(10,10)
x

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [29]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [39]:
array1 = np.arange(1,26)
array = array1.reshape(5,5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [52]:
array[2:5,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [41]:
array1[19]

20

In [55]:
array[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [43]:
array[4]

array([21, 22, 23, 24, 25])

In [59]:
array[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [60]:
np.sum(array)

325

#### Get the standard deviation of the values in mat

In [64]:
np.std(array)

7.211102550927978

#### Get the sum of all the columns in mat

In [65]:
a = np.sum(array[0])
b = np.sum(array[1])
c = np.sum(array[2])
d = np.sum(array[3])
e = np.sum(array[4])
mat = [a , b, c, d, e]
x =np.array(mat)
x

array([ 15,  40,  65,  90, 115])

# Great Job!