In [1]:
import numpy as np

In [3]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
b = np.ones(10)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
print(5*b)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [9]:
c = np.arange(10,51)
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
d = np.arange(0,9)
d = d.reshape(3,3)
print(d)

In [10]:
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
from numpy import random
f = random.rand(1)
print(f)

[0.84710168]


In [16]:
g=random.randn(5,5)
print(g)

[[ 0.40331606  1.6474088   0.68922386 -1.18912323  0.73164219]
 [ 0.20836208  1.60850529 -0.83772495 -0.33444153  1.56047403]
 [-0.37316332 -0.47200502 -0.45146054 -0.59445689  0.29369081]
 [ 0.76509266  0.48262005 -0.89849076 -1.13514554 -0.38699942]
 [ 0.37945186  0.62197709  0.17005945  1.04437536 -0.93157502]]


In [23]:
h=np.arange(0.01,1.01,0.01)
h=h.reshape(10,10)
print(h)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [26]:
i = np.linspace(0,1,20)
i=i.reshape(4,5)
print(i)

[[0.         0.05263158 0.10526316 0.15789474 0.21052632]
 [0.26315789 0.31578947 0.36842105 0.42105263 0.47368421]
 [0.52631579 0.57894737 0.63157895 0.68421053 0.73684211]
 [0.78947368 0.84210526 0.89473684 0.94736842 1.        ]]


In [27]:
j=np.arange(1,26)
j=j.reshape(5,5)
print(j)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [32]:
k=np.arange(12,16)
l=np.arange(17,21)
m=np.arange(22,26)
print(k)
print(l)
print(m)

[12 13 14 15]
[17 18 19 20]
[22 23 24 25]


In [33]:
print(20)

20


In [28]:
n=np.linspace(2,12,3)
n=n.reshape(3,1)
print(k)

[[ 2.]
 [ 7.]
 [12.]]


In [29]:
o=np.arange(21,26)
print(o)

[21 22 23 24 25]


In [ ]:
p=np.arange(16,21)
q=np.arange(21,26)
print(p)
print(q)

In [35]:
print(j.sum())

325


In [36]:
print(np.std(j))

7.211102550927978


In [37]:
print(j.sum(axis=0))

[55 60 65 70 75]
